# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"\x0f\n\rStatusRequest\" \n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x0e\n\x0c\x45ventRequest\"!\n\rEventResponse\x12\x10\n\x08response\x18\x01 \x01(\t2p\n\x0bYourService\x12\x30\n\x0b\x43heckStatus\x12\x0e.StatusRequest\x1a\x0f.StatusResponse\"\x00\x12/\n\x0cTriggerEvent\x12\r.EventRequest\x1a\x0e.EventResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUSREQUEST']._serialized_start=17
  _globals['_STATUSREQUEST']._serialized_end=32
  _globals['_STATUSRESPONSE']._serialized_start=34
  _globals['_STATUSRESPONSE']._serialized_end=66
  _globals['_EVENTREQUEST']._serialized_start=68
  _globals['_EVENTREQUEST']._serialized_end=82
  _globals['_EVENTRESPONSE']._serialized_start=84
  _globals['_EVENTRESPONSE']._serialized_end=117
  _globals['_YOURSERVICE']._serialized_start=119
  _globals['_YOURSERVICE']._serialized_end=231
# @@protoc_insertion_point(module_scope)
